### ISSUE TITLE
Definierbare Templates für Meetingseinstellungen

### ISSUE THREAD

**Issue by tgloeggl** [elan-ev/studip-meeting#302]
The idea is, instead of having the three room-size templates small, medium and large, root can create user-defined templates where the available settings can be predefined, f.e.:
- Seminar-Template: For small groups
- Examination-Template: Camera is forced to be activated
- ...

End-users will then be able to create rooms using these predefined templates, meaning, the can choose from one of the predefined templates and of course make changes to settings for the single room nonetheless.

The templates shall be definable by root in the Meetings-Settings, with a list of already present templates and the abililty to add, edit and remove templates.

Some additional options (for the already present ones) are needed, though, f.e.:
- Autoshare webcam
- Autojoin audio
- Minimize presentation area and user list

The current settings for the different room sizes should be migrated to templates and for fresh meetings installations they should be already present for use. The number of participants alongside a template does not seem be necessary anymore after these changes, so it can be dropped (but please ask the contractor beforehand, if possible / need be. :) ).
The suggested number of participants for a single template can be handled by naming the template accordingly, so thats up to the root user. The predefined templates can than be named something like "Small room (<50 participants)" and so on.

**Comment by tibroc** [comment]
It is possible to configure a video conferncing mode passing these parameters to the `join`-call:

```
userdata-bbb_auto_swap_layout=true
userdata-bbb_show_participants_on_login=false
userdata-bbb_listen_only_mode=false
userdata-bbb_auto_join_audio=true
userdata-bbb_skip_check_audio=true
userdata-bbb_auto_share_webcam=true
userdata-bbb_skip_video_preview=true
```

See also: https://github.com/bigbluebutton/bigbluebutton/issues/11936

**Comment by tgloeggl** [comment]
> It is possible to configure a video conferncing mode passing these parameters to the `join`-call:
> 
> ```
> userdata-bbb_auto_swap_layout=true
> userdata-bbb_show_participants_on_login=false
> userdata-bbb_listen_only_mode=false
> userdata-bbb_auto_join_audio=true
> userdata-bbb_skip_check_audio=true
> userdata-bbb_auto_share_webcam=true
> userdata-bbb_skip_video_preview=true
> ```
> 
> See also: [bigbluebutton/bigbluebutton#11936](https://github.com/bigbluebutton/bigbluebutton/issues/11936)

This would for example achieve the idea of examination-template for a meetings room, with webcams auto-activated.

**Comment by tibroc** [comment]
As of BBB 2.6 these would be the parameters:

```
# Clean-up the Layout:
userdata-bbb_hide_presentation_on_join=true
userdata-bbb_show_participants_on_login=false
# Auto join audio and video:
userdata-bbb_listen_only_mode=false
userdata-bbb_auto_join_audio=true
userdata-bbb_skip_check_audio=true
userdata-bbb_auto_share_webcam=true
```

**Comment by ferishili** [comment]
Hi @tibroc
That would be very helpful if you could give me url containing more info about these new parameters, in order to provide some info text to the users and admins in Stud.IP. I could not find any so far.
Thank in advance
