### ISSUE TITLE
Idea: Link to paste current shared notes back to a Stud.IP Wiki

### ISSUE THREAD

**Issue by tgloeggl** [elan-ev/studip-meeting#347]

**Comment by tibroc** [comment]
This should be possible using the etherpad API on the BBB hosts. However, you would somehow have to configure BBB as well in order to be able to access the etherpad API from outside.

**Comment by tibroc** [comment]
There is one significant problem though: you can not guess the ID of the pad from the meeting metadata and the only way to get the id seems to be by reading it out of the mongodb. This makes the implementation of this feature either quite complicated or very hacky.
