### ISSUE TITLE
Meeting darf max 255 Zeichen lang sein

### ISSUE THREAD

**Issue by Davka** [elan-ev/studip-meeting#438]
Beim Erstellen eines Meetings wird der Veranstaltungsname + den eingegeben Name zum Raumnamen zusammengesetzt.

Das sprengt u.U. die 255 Zeichengrenze

**Comment by ferishili** [comment]
Hi @Davka,
wenn ich es richtig verstanden haben, meinst du in der Datenbank mit mehr als 255 Zeichengrenze? oder?
der Veranstaltungsname ist dynamisch abgerufen und wird in DB nicht gespeichert. deswegen es ist nicht nötig
