### ISSUE TITLE
500: Meetings - Slim Application Internal Error: Call to undefined function ElanEv\Driver\studip_utf8encode()

### ISSUE THREAD

**Issue by Rillke** [elan-ev/studip-meeting#459]
Hi,
we are running Stud.IP 5.2.6 and Meetings 2.70 and we receive the following error when we try to create a DFNVC conference room:

1. Activate Meetings in your course
2. Actions: Add room
3. Fill in room name and select DFNVC
4. Press "create room"
5. see error: `500: Meetings - Slim Application Internal Error: Call to undefined function ElanEv\Driver\studip_utf8encode()`
![image](https://github.com/elan-ev/studip-meeting/assets/2311611/1cb83f07-5461-4a9b-8f31-1105d389fcf2)

The room is created nonetheless but pressing "participate" will possibly throw the same error again or it will send you to the meetings calendar:
![image](https://github.com/elan-ev/studip-meeting/assets/2311611/c44d4ccc-eb9a-4e9d-812d-e6610e5a94d9)

Further information:

`studip_utf8encode()` which was part of the Stud.IP core is removed since 5.0.

The Stud.IP 4.6 implementation:

```php
/**
 * Does not encode anything anymore and just returns the data it received.
 *
 * @deprecated
 *
 * @param mixed $data
 *
 * @return mixed unaltered input $data
 */
function studip_utf8encode($data)
{
    return $data;
}

/**
 * Does not decode anything anymore and just returns the data it received.
 *
 * @deprecated
 *
 * @param mixed $data
 *
 * @return mixed unaltered input $data
 */
function studip_utf8decode($data)
{
    return $data;
}
```

**Comment by ferishili** [comment]
Hi @Rillke
That would be great if you could test the linked PR.

Thanks in advance

**Comment by Rillke** [comment]
Great, thank you! Appears to work, we still have to test with names with some special characters.
