### ISSUE TITLE
Meetings funktioniert nicht, wenn POST verwendet wird

### ISSUE THREAD

**Issue by Davka** [elan-ev/studip-meeting#473]
Unter gewissen Umständen scheint Meetings statt `GET` `POST` für die API-Befehle zu verwenden. Das ist aufgrund einer Sicheitslücke mit den neuesten BBB-Versionen nicht mehr möglich. Auch Scalelite hat hierzu einen FIX

https://github.com/blindsidenetworks/scalelite/releases/tag/v1.5.2

**Comment by omueller54** [comment]
Durch die Änderungen, die mit BBB 2.7.8 POST requests beim join endpoint nicht mehr erlauben, funktioniert insbesondere die Funktion Folien vorab über den Dateibereich in Stud.IP für ein Meeting Raum in BBB bereitzustellen nicht mehr. Sobald man in einem Raum in Stud.IP einen Dateiordner verknüpft hat, der Dateien enthält, lässt sich der BBB Raum über Stud.IP nicht mehr starten.
