### ISSUE TITLE
Errors with cache from Issue #455 for course overview

### ISSUE THREAD

**Issue by olio2** [elan-ev/studip-meeting#474]
The cache from #455 gives errors on our System:

Sometimes this error:
[22-May-2024 14:20:09 Europe/Berlin] PDOException: SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' in /home/studip-dev/studip-5-dev3/studip-5.2.6/lib/classes/StudipPDOStatement.php:156
Stack trace:
#0 /home/studip-dev/studip-5-dev3/studip-5.2.6/lib/classes/StudipPDOStatement.php(156): PDOStatement->execute()
#1 /home/studip-dev/studip-5-dev3/studip-5.2.6/lib/models/SimpleORMap.class.php(575): StudipPDOStatement->execute()
#2 /home/studip-dev/studip-5-dev3/studip-5.2.6/public/plugins_packages/elan-ev/MeetingPlugin/app/models/MeetingCourse.php(60): SimpleORMap::findBySQL()
#3 /home/studip-dev/studip-5-dev3/studip-5.2.6/public/plugins_packages/elan-ev/MeetingPlugin/MeetingPlugin.php(175): ElanEv\Model\MeetingCourse::findByCourseId()
#4 /home/studip-dev/studip-5-dev3/studip-5.2.6/lib/classes/MyRealmModel.php(487): MeetingPlugin->getIconNavigation()

and sometimes this:
Exception: Serialization of 'Closure' is not allowed in /home/studip-dev/studip-5-dev3/studip-5.2.6/public/plugins_packages/elan-ev/MeetingPlugin/MeetingPlugin.php:175

It always has one of those error. Only if the cache part is disabled the Plugin works again.

**Comment by ferishili** [comment]
Please state the following:
- PHP Version
- Stud.IP Version

**Comment by olio2** [comment]
> Please state the following:
> 
> * PHP Version
> * Stud.IP Version

PHP 7.4.33
Stud.IP 5.2.6

**Comment by ferishili** [comment]
Sorry for the delay, I will label this as a bug for now, until further investigation, to make it as a priority to be fixed in the next release!
